### ISSUE TITLE
create test HTML, JS, and CSS

### ISSUE THREAD

**Issue by NickZachary** [PHACDataHub/pelias-canada#112]
```[tasklist]
### Tasks
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/126
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/128
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/146
```

**Comment by NickZachary** [comment]
To replicate the functionality of the Python script into a web-based application using HTML, JavaScript, and CSS, we'll create a simple web page that allows users to upload a CSV file, perform reverse geocoding using an API, and download the processed output as a CSV file. We'll use JavaScript for handling file uploads, making API requests, and updating the UI dynamically.

### HTML (`index.html`)

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reverse Geocoding</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>Reverse Geocoding</h1>
        <input type="file" id="csvFileInput" accept=".csv" onchange="handleFileUpload(event)">
        <br><br>
        <button onclick="processCSV()">Process CSV</button>
        <br><br>
        <a id="downloadLink" style="display:none;">Download Output CSV</a>
    </div>

    <script src="script.js"></script>
</body>
</html>
```

### CSS (`styles.css`)

```css
body {
    font-family: Arial, sans-serif;
    background-color: #f0f0f0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
}

.container {
    text-align: center;
    background-color: #fff;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0,0,0,0.1);
    max-width: 600px;
    width: 100%;
}

button {
    padding: 10px 20px;
    font-size: 16px;
    cursor: pointer;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 4px;
}

button:hover {
    background-color: #0056b3;
}

input[type="file"] {
    display: none;
}
```

### JavaScript (`script.js`)

```javascript
// Function to handle file upload
function handleFileUpload(event) {
    const file = event.target.files[0];
    if (file) {
        // Validate file type
        if (!file.name.endsWith('.csv')) {
            alert('Please upload a CSV file.');
            return;
        }
        // Store uploaded file in global variable
        window.uploadedFile = file;
        console.log(`Uploaded file: ${file.name}`);
    }
}

// Function to perform reverse geocoding
async function reverseGeocode(lat, lon) {
    const base_url = "https://geocoder.alpha.phac.gc.ca/api/v1/reverse?";
    const params = new URLSearchParams({
        "point.lat": lat,
        "point.lon": lon
    });

    try {
        const response = await fetch(base_url + params);
        if (!response.ok) {
            throw new Error('Failed to fetch geocoding data.');
        }
        const data = await response.json();
        return data;
    } catch (error) {
        console.error('Error in reverse geocoding:', error);
        return null;
    }
}

// Function to prioritize and extract relevant properties
function prioritizeFeatures(features) {
    if (!features || features.length === 0) {
        return null;
    }

    // Sort features by confidence (descending), then by distance (ascending)
    features.sort((a, b) => {
        const confidenceA = a.properties.confidence || 0;
        const confidenceB = b.properties.confidence || 0;
        if (confidenceA !== confidenceB) {
            return confidenceB - confidenceA; // Sort by confidence descending
        } else {
            const distanceA = a.properties.distance || 0;
            const distanceB = b.properties.distance || 0;
            return distanceA - distanceB; // Sort by distance ascending
        }
    });

    // Extract relevant properties from top feature
    const topFeature = features[0];
    const properties = topFeature.properties;
    const coordinates = topFeature.geometry.coordinates;

    const result = {
        coordinates: coordinates,
        name: properties.name || '',
        housenumber: properties.housenumber || '',
        street: properties.street || '',
        confidence: properties.confidence || '',
        distance: properties.distance || '',
        accuracy: properties.accuracy || '',
        country: properties.country || '',
        region: properties.region || '',
        region_a: properties.region_a || '',
        county: properties.county || '',
        county_gid: properties.county_gid || '',
        locality: properties.locality || '',
        neighbourhood: properties.neighbourhood || '',
        label: properties.label || ''
    };

    return result;
}

// Function to process uploaded CSV file
async function processCSV() {
    const file = window.uploadedFile;
    if (!file) {
        alert('Please upload a CSV file.');
        return;
    }

    // Read CSV file content
    const reader = new FileReader();
    reader.onload = async function(event) {
        const csvContent = event.target.result;
        const rows = csvContent.split('\n');
        const headers = rows[0].split(',');

        // Find index of relevant columns
        const latIndex = headers.findIndex(header => header.trim().toLowerCase() === 'ddlat');
        const lonIndex = headers.findIndex(header => header.trim().toLowerCase() === 'ddlong');
        const inputIDIndex = headers.findIndex(header => header.trim().toLowerCase() === 'inputid');

        if (latIndex === -1 || lonIndex === -1 || inputIDIndex === -1) {
            alert('Columns "ddLat", "ddLong", or "inputID" not found.');
            return;
        }

        // Process each row
        const results = [];
        for (let i = 1; i < rows.length; i++) {
            const columns = rows[i].split(',');
            const lat = parseFloat(columns[latIndex]);
            const lon = parseFloat(columns[lonIndex]);
            const inputID = columns[inputIDIndex];

            if (!isNaN(lat) && !isNaN(lon)) {
                const geocodingData = await reverseGeocode(lat, lon);
                if (geocodingData && geocodingData.features) {
                    const result = prioritizeFeatures(geocodingData.features);
                    if (result) {
                        result.inputID = inputID;
                        results.push(result);
                    }
                }
            }
        }

        // Convert results to CSV and create download link
        const csvContentOutput = results.map(result => Object.values(result).join(',')).join('\n');
        const blob = new Blob([csvContentOutput], { type: 'text/csv' });
        const downloadLink = document.getElementById('downloadLink');
        downloadLink.href = URL.createObjectURL(blob);
        downloadLink.download = 'output.csv';
        downloadLink.style.display = 'inline';
    };

    reader.readAsText(file);
}
```

### Explanation:

1. **HTML Structure**: Provides the basic structure of the web page with a file input, process button, and a download link for the output CSV file.

2. **CSS Styles**: Basic styling for the elements to ensure readability and user-friendly interface.

3. **JavaScript Logic**:
   - **File Upload Handling**: `handleFileUpload` function captures the uploaded CSV file and stores it in a global variable.
   - **Reverse Geocoding**: `reverseGeocode` function performs the API request to fetch reverse geocoding data based on latitude and longitude.
   - **Prioritizing Features**: `prioritizeFeatures` function sorts and extracts relevant properties from the geocoding results.
   - **CSV Processing**: `processCSV` function reads the uploaded CSV file, extracts necessary columns ('ddLat', 'ddLong', 'inputID'), performs reverse geocoding for each row, prioritizes the results, and generates an output CSV file.
   - **Output CSV Download**: The output CSV content is converted to a Blob and set as the href of the download link (`downloadLink`), which allows users to download the processed data.

This setup provides a basic implementation. Depending on your specific requirements and environment, you might need to adjust the API endpoints, error handling, or additional UI features.

**Comment by NickZachary** [comment]
[testRgeo.csv](https://github.com/user-attachments/files/16152023/testRgeo.csv)
Here is the test file ^^^

**Comment by NickZachary** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reverse Geocoding</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>Reverse Geocoding</h1>
        <input type="file" id="csvFileInput" accept=".csv" onchange="handleFileUpload(event)">
        <br><br>
        <button onclick="processCSV()">Process CSV</button>
        <br><br>
        <a id="downloadLink" style="display:none;">Download Output CSV</a>
    </div>

    <script src="script.js"></script>
</body>
</html>

**Comment by NickZachary** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reverse Geocoding</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>Reverse Geocoding</h1>
        <div>
            <input type="file" id="csvFileInput" accept=".csv" style="display: none;" onchange="handleFileUpload(event)">
            <label for="csvFileInput" class="file-upload-label">Choose CSV File</label>
            <progress id="fileUploadProgress" style="display: none;"></progress>
        </div>
        <br>
        <button id="processButton" onclick="processCSV()" disabled>Process CSV</button>
        <button id="stopButton" onclick="stopProcessing()" style="display: none;">Stop Processing</button>
        <br><br>
        <a id="downloadLink" style="display:none;">Download Output CSV</a>
    </div>

    <script src="script.js"></script>
</body>
</html>

**Comment by NickZachary** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reverse Geocoding</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>Reverse Geocoding</h1>
        <div>
            <input type="file" id="csvFileInput" accept=".csv" style="display: none;" onchange="handleFileUpload(event)">
            <label for="csvFileInput" class="file-upload-label">Choose CSV File</label>
            <progress id="fileUploadProgress" style="display: none;"></progress>
        </div>
        <br>
        <button id="processButton" onclick="processCSV()" disabled>Process CSV</button>
        <button id="stopButton" onclick="stopProcessing()" style="display: none;">Stop Processing</button>
        <br><br>
        <a id="downloadLink" style="display:none;">Download Output CSV</a>
    </div>

    <script src="script.js"></script>
</body>
</html>

**Comment by NickZachary** [comment]
[reverseGeocode_website_v1.zip](https://github.com/user-attachments/files/16163870/reverseGeocode_website_v1.zip)

**Comment by NickZachary** [comment]
https://codepen.io/Niko-sy/pen/xxobXWB

**Comment by NickZachary** [comment]
[reverseGeocode_website_v2.zip](https://github.com/user-attachments/files/16164061/reverseGeocode_website_v2.zip)

**Comment by NickZachary** [comment]
[reverseGeocode_website_v3.zip](https://github.com/user-attachments/files/16164313/reverseGeocode_website_v3.zip)
