### ISSUE TITLE
Epic - UI task list

### ISSUE THREAD

**Issue by GRaganold** [PHACDataHub/pelias-canada#64]
```[tasklist]
### V1  Feature list:
- [ ] Feature - UI - BulkInput.jsx refactor 
- [ ] Feature - UI - Python and R code zip files
- [ ] Feature - UI - data error handling
- [ ] Feature - UI - epoch and datum
- [ ] Feature - UI - language 
- [ ] Feature - UI - reverse lookup
- [ ] Task - UI - Locate me button
```

```[tasklist]
### V1  Feature list:
- [ ] Feature - UI - Kibana Integration
- [ ] Feature - UI - HELK Integration

```
