### ISSUE TITLE
Feature - UI - BulkInput.jsx refactor

### ISSUE THREAD

**Issue by GRaganold** [PHACDataHub/pelias-canada#65]
```[tasklist]
###  Task list:
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/67
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/68
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/69
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/70
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/71
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/72
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/73
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/74
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/75
```
