### ISSUE TITLE
Feature - UI - data error handling

### ISSUE THREAD

**Issue by NickZachary** [PHACDataHub/pelias-canada#81]
```[tasklist]
### Tasks
- [ ] create master test data for iterative use w/ Pelias API
- [ ] design, test, and report Type I  and Type II Errors
- [ ] incorporate testing results into file accompanying downloaded metadata with geocoding results
```
