### ISSUE TITLE
Feature - UI - reverse lookup

### ISSUE THREAD

**Issue by NickZachary** [PHACDataHub/pelias-canada#82]
```[tasklist]
### Tasks
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/83
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/84
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/112
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/113
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/114
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/122
- [ ] https://github.com/PHACDataHub/pelias-canada/issues/140
```
